name: Lint

on: [push, pull_request]

env:
  DAY_OF_WEEK: Monday

jobs:
  lint_name:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
      - name: "тестирую гитхаб переменные"
        run: |
          echo "Имя текущего воркфлоу – $GITHUB_WORKFLOW"
          echo "Branch name: $GITHUB_REF"
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run Ruff Lint
        run: |
          make lint
